### ISSUE TITLE
Unable to generate report using Analyzer

### ISSUE THREAD

**Issue by Droidmannn** [iSECPartners/Introspy-Analyzer#10]
Tried executing the below command 
python -m introspy -p ios -o output -f <ip address of ios device>
Asked for password - gave the password
Then the db file got listed and i gave the number and pressed enter.
I am getting 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/introspy/__main__.py", line 7, in <module>
    sys.exit(introspy.main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/introspy/**init**.py", line 122, in main
    analyzedDB = DBAnalyzer(db_path, androidDb)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/introspy/DBAnalyzer.py", line 14, in **init**
    super(DBAnalyzer, self).**init**(dbPath, androidDb)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/introspy/DBParser.py", line 29, in **init**
    for row in SqlConn:
sqlite3.DatabaseError: database disk image is malformed

Am i missing something here?

**Comment by vjunnu** [comment]
I am facing the same issue although on IOS

**Comment by askmegit** [comment]
I am facing the same issue although on IOS
